baseURL = "/"
languageCode = "en-us"
title = "Words"
theme = "hugo-paper"
pygmentsStyle = "monokailight"

[menu]

  [[menu.main]]
    identifier = "github"
    name = "github"
    url = "https://github.com/saulecabrera"

  [[menu.main]]
    identifier="twitter"
    name = "twitter"
    url = "https://twitter.com/saulecabrera"
